name: Deploy Backend to Azure

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'simple-backend/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    
    - name: Install dependencies
      run: |
        cd simple-backend
        npm ci --production
    
    - name: Create deployment package
      run: |
        cd simple-backend
        zip -r ../backend-deploy.zip . -x "*.git*"
    
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'cbbs-node-web'
        publish-profile: ${{ secrets.AZURE_BACKEND_PUBLISH_PROFILE }}
        package: backend-deploy.zip
